version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    - echo "Deployed to S3"
    - aws cloudfront create-invalidation --distribution-id E28RA7EMA2X36R --paths "/*"
artifacts:
  files:
    - '**/*'
